# Day 1: Sentences 

`r newthought("We will cover several different")` techniques for editing and rewriting
your manuscript, and they will target different parts (e.g., Introduction, Results) or 
levels (e.g., paragraphs, sentences) of your manuscript. Some will take a lot of mental 
work and editing to put in place. We will start, however, with some techniques that
are easy to do, and make a huge difference in how easy your manuscript is to read, but
that are underused in science. These techniques focus on editing at the sentence level.

To learn these techniques, you will be reading several chapters of the Joseph
Williams book (*Style*). If you haven't received that one yet, you can find link
to an online scan of an earlier version (like the one I've sent you)
[here](https://sites.duke.edu/niou/files/2014/07/WilliamsJosephM1990StyleTowardClarityandGrace.pdf).

The techniques are revisited in the other books I sent, all of which are built on 
the ideas that *Style* presents. I'll include some suggestions for additional readings 
from some of the other books, and you can use that if you feel like you haven't mastered
the ideas yet from reading the *Style* chapters (or if you're so excited about them you 
want to see more examples!). If you'd like examples from scientific writing, you can find 
them in the suggested additional reading from *Writing Science in Plain English* and 
*Writing Science*. 

1. **Read Chapter 1 from *Style*.** 

This first chapter sets up Joseph Williams's goals and philosophy for the book,
and it captures nicely what we'll be trying to do through our workshop this
week. Notice in particular that we won't be focusing on "correct" or grammatical
writing, but instead on editing to make things easier for our readers.

2. **Exercise: Read and rank the three example papers**

In the
[Introduction](https://geanders.github.io/writing_workshop/1-1-readings-for-the-workshop.html#readings-for-the-workshop),
I've included links to three papers that we'll use as examples, in addition to
working with your own manuscripts. Read these three papers and rank them (1 as
best to 3 as worst) in terms of: (1) how easy you found it to read; (2) how much
you enjoyed reading it; (3) how much you learned by reading it.

3. **Read Chapter 2 from *Style*.**

This chapter explains how you can think of sentences in terms of characters and 
their actions, and how you can diagnose if a sentence is not divided into 
subject and verb in a way that highlights these elements. While it may seem that
this idea would be more important in fiction, this chapter provides examples of how
it can clarify sentences in academic writing.

*Additional reading.* If you would like more information on the ideas in this
chapter of *Style*, you can also check out Chapter 3 from *Writing Science in Plain English*
and Chapter 14.2 ("A First Principle: Stories and Grammar") from *The Craft of Research* 
(note: I currently have an earlier edition of this book. I'll be getting the second edition, 
like you have, soon. I will update this chapter number if it has changed in the second 
edition).

4. **Identify the characters in the example papers.**

In the three example papers, re-read the Introductions. List three to five main 
characters in the Introduction of each paper, using the explanation of "main characters"
that Joseph Williams provides in Chapter 2 of *Style*. Remember that, in some cases, 
characters can be concepts. 

Next, identify the characters in the following sentence:

> "The use of the ecological fallacy to explain the discrepancy between
individual and ecological correlations may have unintended consequences."
Schwartz, 1994

Try to rewrite the sentence to conform with the first two principles of clear
writing (p. 21 of the online version of *Style*).

Do the same with the following sentence (it may help to replace the semi-colon
with a period and diagnose / fix the resulting two sentences separately): 

> "For these reasons, using Twitter appropriately can be more than just a social
media activity; it can be a real career incubator in which researchers can
develop their professional circles, launch new research projects and get helped
by the community at various stages of the projects." Cheplygina et al., 2020

5. **Identify the characters in a paragraph of your manuscript.**

Pick a paragraph of your manuscript. List three to five main characters in that paragraph.
In the sentences in these paragraphs, are the main characters the subjects of the 
sentences? Are there any examples where the action is in abstract nouns (e.g., knowledge, 
determination) rather than in verbs (e.g., know, determine)?

Pick one sentence of this paragraph. Rewrite it two ways. First, rewrite it in a way that
violates the first two principles of clear writing (p. 21 of the online version of *Style*)
and then in a way that conforms with these principles. 

Next, read through the full paragraph and try to diagnose every sentence that is
problematic, from this perspective. Use the following advice from the *Style*
book:


> "A quick method is simply to run a line under the first five or six words of
every sentence. If you find that (1) you have to go more than six or seven words
into a sentence to get past the subject to the verb and (2) the subject of the
sentence is not one of your characters, take a hard look at that sentence; its
characters and actions probably do not align with subjects and verbs."

If you do not find any in this paragraph, look through other paragraphs in your 
manuscript. Write down up to three sentences that you find, and we'll work together
to diagnose if they do indeed have this problem and, if so, fix them.

6. **Identify and replace nominalizations.**

In Chapter 2 of *Style*, Joseph Williams defines *nominalizations* and explains how 
they can confound clarity in a sentence. Identify any nominalizations in the following
sentence: 

> "We begin with a description of the validity framework and the definition of
key terms." Schwartz, 1994

Rewrite the sentence without any nominalizations. 

Next, find three sentences from your own manuscript with nominalizations. There
are some tips in the section in Chapter 2 on "Looking for Nominalizations".
Write these down, and then try rewriting them to remove the nominalizations.

7. **Editing sentences in a paragraph.**

Using all the techniques from Chapter 2, diagnose problems in the following 
paragraph and rewrite it: 

> "Natural hazard losses exhibit an upward trend over time. This is a function
of increases in wealth and population but is also attributed to better loss
accounting in recent years. The escalating pattern of hazard losses is therefore
partially an artifact of advances in reporting losses, but how much or how
little this effect contributes to the skyrocketing losses in comparison to
effects of population growth and increasing wealth in high hazard areas is
unclear." Gall et al., 2009

**All the following steps are things for you to try after our workshop 
meeting on "Sentences".**

8. **Read Chapter 3 from *Style*.**

This chapter takes the next step---it starts considering how sentences fit 
within a paragraph, and how ordering the information in the sentence can 
help the flow across the paragraph. 

*Additional reading.* If you would like more information on the ideas in this
chapter of *Style*, you can also check out Chapter 7 from *Writing Science in 
Plain English*, Chapter 12 in *Writing Science*, and Chapter 14.3 from 
*The Craft of Research*.

9. **Identify topics in a paragraph of your manuscript.**

Pick a paragraph of your manuscript. Identify all the topics in the paragraph. 
Is there a consistent topic string, as defined in Chapter 3 of *Style*? 
Are your topics visible? Revise your paragraph based on this diagnosis.

Next, read through all the paragraphs in your manuscript. Highlight the topics
throughout. Are there certain sections where it looks like the topics might not
be very visible, or where there may be too many topics in a paragraph?

10. **Read Chapter 4 from *Style*.**

This chapter discusses strategies for ending sentences, to emphasize the point
you want to emphasize. This chapter is helpful, but you'll get more immediate
milage from mastering the content in Chapters 2 and 3. For now, read through
this chapter so you can mull it over, but I don't have any exercises for you
based on it.

