# Day 2: Openings

`r newthought("On Day 1, we focused on mechanics")` rather than content. Today,
we'll talk about content, focusing on your Introduction. I usually find this
section the hardest to write, and I'll often put it off until last. You need to
draw in your reader and convince him or her that the rest of the paper is worth
reading (and, for a research article, that the science was worth doing). If a
reviewer is going to hate your paper, he or she often decides by the end of the
Introduction (based on review comments I've gotten for past papers). And while
the other reviewers won't decide that they love it by that point, they can be
convinced that they are in reasonably good hands, and that you are competent in
the area and familiar with the field and open problems in it.

*Writing Science* discusses the job of an Introduction in a scientific paper,
and how an Introduction can fail. For today's meeting, you'll be reading through
several chapters in this book, evaluating whether and how the Introductions in
the three example papers do their job, thinking about how to frame the
Introduction for your manuscript.

1. **Summarize your manuscript.**

In 2--3 sentences, describe what your manuscript covers. 

In 2--3 more sentences, explain why your manuscript is important in advancing
science in your field.

2. **Read Chapter 4 of *Writing Science*.**

This chapter explains common story structures, and how they can be applied
to scientific writing. Near the end of this chapter (section 4.3), it presents
the key components of a paper's Introduction, Methods, Results, and Discussion. 

3. **Identify key Introduction components in an example paper.**

Re-read the Introductions of the example papers by Cheplygina et al. and 
Schwartz. Try to identify the following components in the Introduction: 

- What is the larger problem that the paper will be tackling?
- What is the relevant context for that problem?
- What are the key characters?
- What background information is given to help the reader understand 
the specific work in the paper?
- What is the "challenge" ("the specific hypotheses/questions/goals of
the current work")?

Go through each of these two Introductions and use three different colors to
highlight elements that you think are part of the Opening, the Background, and
the Challenge, based on how those parts are explained in this chapter. (You will
be reading other chapters today that go deeper into these ideas, so you may come
back and revise your answers based on your later reading.)

4. **Read Chapter 5 of *Writing Science*.**

This chapter covers the very first part of the Introduction, which the author
calls the "Opening".

5. **Diagnose the Opening for an example paper.**

Re-read the first paragraph of the Schwartz paper. Based on this paragraph, who
do you think is the intended audience for the paper? What is the larger issue
the paper will address? Do you think that they are properly "advertising" what
they will later cover in the paper?

6. **Define Opening components for your paper.**

Write down the following for your own manuscript: 

- What is the target audience? Is it broad / interdisciplinary or targeted to
researchers in a certain field?
- What is the larger issue that the manuscript will address? In writing this, be
sure to be clear about the scope with which the manuscript will cover this
issue.
- What are a few elements of the issue that are interesting but that your
manuscript will **not** address?

7. **Revise the Opening for your manuscript.**

Take a look at the first paragraph of your Introduction in the context of your
answers to the questions in the previous prompt. Does your Opening need the
whole paragraph, or just the first sentence or two? Does this first paragraph
include any signals to clarify what audience you expect for the manuscript? Does
the paragraph give readers clues on the larger issue that the manuscript will
address? Does the paragraph "overpromise", indicating that the manuscript will
cover a larger scope than it does?

Write a revised version of your first paragraph where you address any
limitations of your previous draft of your Opening.

**All the following steps are things for you to try after our workshop 
meeting on "Openings".**

8. **Read Chapters 6 and 7 of *Writing Science*.**

Chapter 6 covers how to move from the Opening of your Introduction to the
Challenge that you present before moving into other parts of your paper. Chapter
7 discusses how to end an Introduction with a "Challenge," motivating everything
you present in the rest of the manuscript.

9. **Evaluate the Funnel and Challenge of example papers.**

Re-read the Introductions for the three example papers. Find and write down the
text in each paper that presents the Challenge of the paper.

Next, re-read the Introduction of the Gall et al. paper. How does the
Introduction funnel the readers from the Opening to the Challenge at the end of
the Introduction? What background information does it give readers to help them
understand and appreciate the Challenge? What examples do they use from the
literature to convince readers that their Challenge is important?

10. **Define the Challenge of your manuscript.**

In 1--2 sentences, write the Challenge of your manuscript. 

Look at the draft of your Introduction. Is this Challenge clear in the text? If
so, is it at the end of the Introduction, or somewhere else?

Write down three pieces of background information that you think it is critical
for your reader to know to believe that your manuscript's Challenge is
important. Draft a paragraph one each of these explaining and presenting the
background information to readers.

Write down two examples that you think might help readers understand why your
Challenge is important. Draft a few sentences presenting each of these examples.

Revise your Introduction to integrate your drafted material on the background
and examples.

11. **Read Chapters 8 and 9 of *Writing Science*.**

These next two chapters move into advice on writing the body of the manuscript
(the "Action", which often includes Methods and Results) and the "Resolution"
(typically the Discussion). Think about what you're hoping to achieve through
these later parts of your manuscript.

