# Day 3: Paragraphs

`r newthought("Today, we'll be moving back")` from content to mechanics. Today,
we'll talk about editing for clarity at a different level, the level of
paragraphs. We will look at how we can move around text in a paragraph to make
it easier for a reader to quickly understand what they should get out of a
paragraph and to easily follow ideas in the paragraph.

To learn these techniques, you will be reading several chapters of the Joseph
Williams book (*Style*). If you haven't received that one yet, you can find link
to an online scan of an earlier version (like the one I've sent you)
[here](https://sites.duke.edu/niou/files/2014/07/WilliamsJosephM1990StyleTowardClarityandGrace.pdf).

The techniques are revisited in the other books I sent, all of which are built
on the ideas that *Style* presents. I'll include some suggestions for additional
readings from some of the other books, and you can use that if you feel like you
haven't mastered the ideas yet from reading the *Style* chapters. If you'd like
examples from scientific writing, you can find them in the suggested additional
reading from *Writing Science in Plain English* and *Writing Science*.

1. **Reach Chapter 5 of *Style* (online version).**

This chapter discusses how to structure paragraphs so they seem to "hang
together". It presents techniques for diagnosing and fixing problems with
thematic strings to help make a paragraph more coherent, as well as how to order
the issue and discussion within a paragraph.

*Additional reading.* If you would like more information on the ideas in this
chapter of *Style*, you can also check out Chapter 10 from *Writing Science in 
Plain English*.

2. **Identify thematic strings in a paragraph from an example paper.**

Re-read this paragraph from the Cheplygina et al. paper. When you first read
this paragraph, did you find it easy or hard to read?

> "Even if you use Twitter only for professional purposes, consider opening up a
little bit to show your followers you are a real person. People outside your
field are not likely to follow you if your tweets are only about sharing events,
articles, and positions in your own field. You need to add an extra
ingredient---your opinions, or something personal---to what you share. One way to do
this is through sharing failures: a rejected paper or job application, or even a
spilt coffee. This is a great way to give and receive moral support from other
academics."

With the above paragraph, do the following exercise from Chapter 5 of *Style* 
(without re-reading the paragraph!):

> "Make two lists. In one, list the characters you remember. In the other, list
just two or three words that would capture the central concepts that the writer
weaves around those characters, words that constitute the conceptual center of
that paragraph."

Go back and look at the paragraph. Do the thematic strings in the paragraph 
agree with the characters and concepts that you remembered and listed?

3. **Identify thematic strings in a paragraph from your manuscript.**

Pick a paragraph from your manuscript that you think "hangs together". Do the same
exercise for this paragraph and identify the thematic strings. 

Next pick a paragraph from your manuscript that feels vague when you re-read it.
Do the same exercise, and see if you can revise the paragraph so that its
thematic strings are consistent and clear.

4. **Identify the issue in paragraphs from example papers.**

Chapter 5 of *Style* defines the *issue* of a paragraph as the part that aims
"to put before the reader concepts or claims that the writer intends to expand
on in what follows."

For the paragraph from prompt 2, the first sentence oseems to be its issue: 

> "Even if you use Twitter only for professional purposes, consider opening up a
little bit to show your followers you are a real person."

What theme is introduced at the end of this issue? Does the rest of the
paragraph follow through in talking about this theme? From the current version
of the issue sentence, is it easy to pick out the main concept that will be
developed in the rest of the paragraph (the discussion)?

Next, re-read the following paragraph from the Gall et al. paper:

> "A more subtle form of introducing hazard bias arises from issues of the
definition of the hazard and assigning loss estimates (by the original data
source) to predefined hazard categories within a database. This is most apparent
in the management of complex events involving multiple hazards versus a singular
hazard event. A tornado spawned by a hurricane is counted as a unique tornado
event, but it could also be lumped together within the entire hurricane event,
or both. Each loss database classifies events differently, especially when they
involve multiple hazard types (Guha-Sapir and Below 2002). Inconsistent naming
conventions and classification methodologies aggravate this problem and can
result in different (and/ or artificial) hazard categories for similar, if not
identical events. For example, Downton et al. (2005) reveal a $520 million
"flood" loss in FEMA's database that was not in the NWS data. The discrepancy is
a result of differences in how each agency defines what constitutes a flood
event. In this case, the event (storm surge) was outside NWS's definition of a
flood."

Highlight the text that gives the issue in this paragraph. What theme is identified
at the end of the issue sentence? Does the rest of the paragraph follow through
on this theme?

In the following version of the paragraph, I have rewritten the first sentence.
Does this version of the paragraph seem more or less coherent that the original
version? Identify the differences in the structure of the two versions of the
sentence that contribute to coherence of the paragraph.

> "**More subtly, hazard bias arises because databases differ in how
they define disasters and sort hazards into predefined categories.** This is
most apparent in the management of complex events involving multiple hazards
versus a singular hazard event. A tornado spawned by a hurricane is counted as a
unique tornado event, but it could also be lumped together within the entire
hurricane event, or both. Each loss database classifies events differently,
especially when they involve multiple hazard types (Guha-Sapir and Below 2002).
Inconsistent naming conventions and classification methodologies aggravate this
problem and can result in different (and/ or artificial) hazard categories for
similar, if not identical events. For example, Downton et al. (2005) reveal a
$520 million "flood" loss in FEMA's database that was not in the NWS data. The
discrepancy is a result of differences in how each agency defines what
constitutes a flood event. In this case, the event (storm surge) was outside
NWS's definition of a flood."

5. **Identify the issue in paragraphs from your manuscript.**

Pick a series of four or five paragraphs in your manuscript. For each paragraph, 
highlight the sentence that states the issue. What concept is presented at the end
of that sentence? Highlight places in the rest of that paragraph that 
follow up on that theme. Are there any thematic strings in the rest of the
paragraph that weren't "announced" in the issue sentence?

Re-write the issue sentence of each paragraph. As you do, keep in mind the 
advice from the "Sentences" section on characters and actions. Also, make sure
that you place the theme you want to develop at the end of the issue sentence.

6. **Identify the issue in every paragraph of your manuscript.**

Now go through your entire manuscript and highlight the issue sentence in each
paragraph.

This should help highlight the structure of your paper and the major ideas you
are trying to share. Do your issues agree with what your goals for this paper?
Do they align with the "Challenge" at the end of your Introduction?

Make two lists: one with any issues that are in your paper but do not align with
your Introduction's Challenge and one with any points that you were hoping to
make in your manuscript but that aren't yet in the issue of a paragraph. Use
these two lists to mark paragraphs that you might consider cutting (or revising)
and to add "placeholders" for spots where you want to add paragraphs to address
issues you've missed.

**All the following steps are things for you to try after our workshop 
meeting on "Paragraphs".**

7. **Diagnose and revise a paragraph from an example paper.**

Re-read the following paragraph from the Schwartz paper. What are the main characters
in this paragraph (revisit Chapter 2 of *Style* if you need a refresher)? What are 
the topic strings (revisit Chapter 3 of *Style* for a description)? What
are the thematic strings? Once you have written down each of these, revise
the paragraph to make it more focused and easier to read. 

> "The question of disease etiology is complex. It is likely that a multitude of
causes is involved in the development of any particular disease. Where in the
causal chain, among the myriad of variables, one chooses to examine and
ascertain causation is often a question of where intervention is most
efficacious. That, in turn, is often a political and not a scientific issue. An
examination of the full range of variables potentially involved in disease
etiology, with a synthesis of findings from all levels of analysis, provides the
best opportunity for a full understanding of disease etiology."

**Try yourself before reading the next paragraph!** Here's my take. If I were
really working on this paper, I'd probably go make to the original author
with this paragraph to make sure that I haven't changed any of what she meant
to say with the edits.

> "It is hard to figure out what causes a disease. Often, many causes
contribute, through a complex causal chain. When researchers try to clarify
this causal chain, their research is often framed by the question: which
interventions work best? However, an intervention succeeds or fails
as much from politics as from science. Research should instead  
consider all the factors that might contribute to the disease's causal 
chain, and when results are available at different levels of analysis, 
they should be synthesized. Doing so provides our best opportunity
to fully understand disease etiology."

8. **Revise the issue sentence in each paragraph of your manuscript.**

Using what we've covered in "Sentences" and today, revise all the issue
sentences in your manuscript. Make sure that you place the concept that you want
to discuss in the paragraph at the end of the issue sentence.

9. **Read Chapter 6 of *Style* (online version).**

This chapter continues to discuss how paragraphs can be made more coherent. 
Think about the content in this chapter in terms of which paragraphs of your
manuscript have a point that comes at the end of the paragraph rather than 
at the end of the paragraph's issue. 

For the paragraph where you state your paper's "Challenge", this will almost
always be the case. Are there other paragraphs in your manuscript where this is
also the case? If this is not the case for the last paragraph of your
Introduction, do you think that paragraph would be more effective if you moved
the point to the end?

*Additional reading.* If you would like more information on the ideas in this
chapter of *Style*, you can also check out Chapter 11 from *Writing Science*.
As a follow-up, you might also want to check out Chapter 11 from *Writing Science
in Plain English*, which discusses how to arrange paragraphs. 
