# Day 4: Arguments

`r newthought("Today, we'll move back")` to content. We'll talk about how to
present and support arguments in your manuscript. By "arguments", I don't
necessarily mean statements that are likely to cause strong disagreement, but
rather points that we're trying to convince the readers of. In this sense, the
"arguments" we'll talk about today have a lot to do with the paragraph "points"
covered in Chapter 6 of *Style* (which you'll read after our Day 3 meeting).

*The Craft of Research* has a whole section on presenting and building arguments
in a paper. This book is meant more for students who are writing reports or
theses, rather than people writing scientific manuscripts. However, it has a
whole section that usefully presents key ideas behind making arguments in your
writing. I have found it very useful to revisit these ideas when I feel like I'm
not making a point well in a manuscript.

The ideas we'll talk about today fall into the general category of *rhetoric*.
We don't teach this as much as we should. We'll only get a taste today, but it's
a topic worth exploring more as you continue to work on writing and other forms
of communication to share your science.

1. **Read Chapter 7 and 8 of *The Craft of Research*.**

These chapters give an overview of making arguments in writing and then 
explain how to make claim. 

2. **Identify claims in the example papers.**

Re-read the two first paragraphs in the Chelygina et al. paper. Highlight
a single claim that you think is the most important claim made in this
section: 

> "Twitter is one of the most popular social media platforms, with over 320
million active users as of February 2019. Twitter users can enjoy free content
delivered by other users whom they actively decide to follow. However, unlike in
other areas where Twitter is used passively (e.g., to follow influential figures
and/or information agencies), in science it can be used in a much more active,
collaborative way: to ask for advice, to form new bonds and scientific
collaborations, to announce jobs and find employees, to find new mentors and
jobs. This is particularly important in the early stages of a scientific career,
during which lack of collaboration or delayed access to information can have the
most impact. 

> "For these reasons, using Twitter appropriately [1] can be more than
just a social media activity; it can be a real career incubator in which
researchers can develop their professional circles, launch new research projects
and get helped by the community at various stages of the projects. Twitter is a
tool that facilitates decentralization in science; you are able to present
yourself to the community, to develop your personal brand, to set up a dialogue
with people inside and outside your research field and to create or join
professional environment in your field without mediators such as your direct
boss."

Re-read the following paragraph in the Gall et al. paper. Highlight
a single claim that you think is the most important claim in this paragraph:

> "A more subtle form of introducing hazard bias arises from issues of the
definition of the hazard and assigning loss estimates (by the original data
source) to predefined hazard categories within a database. This is most apparent
in the management of complex events involving multiple hazards versus a singular
hazard event. A tornado spawned by a hurricane is counted as a unique tornado
event, but it could also be lumped together within the entire hurricane event,
or both. Each loss database classifies events differently, especially when they
involve multiple hazard types (Guha-Sapir and Below 2002). Inconsistent naming
conventions and classification methodologies aggravate this problem and can
result in different (and/ or artificial) hazard categories for similar, if not
identical events. For example, Downton et al. (2005) reveal a $520 million
"flood" loss in FEMA's database that was not in the NWS data. The discrepancy is
a result of differences in how each agency defines what constitutes a flood
event. In this case, the event (storm surge) was outside NWS's definition of a
flood."

Page 123 of *The Craft of Research* gives several categories for types of
claims. What type of claim do you think is being made in each of the two
paragraphs above? Do you think each is more conceptual or more practical?
Does this agree with the surrounding content of the paper (i.e., is it trying
to change the readers mind or trying to make the reader do something)?
Do either of the claims include a hedge or qualification?

3. **Identify and revise a claim in your manuscript.**

Pick a paragraph of your manuscript where you are making an important claim.
Highlight the sentence that makes the key claim in that paragraph.

Based on Chapter 8 of *The Craft of Research*, describe and assess this claim. 
What type of claim is it (see p. 123)? Is it practical or conceptual? Is it 
too weak or too strong, given what you think you can reasonable claim based on 
your evidence and logic? Is the claim specific? Is your claim significant?

Revise the claim based on your assessment. If you are trying to get the readers
to do something with your paper, make sure it is a claim of action. If you 
are trying to change readers minds, make sure it is a conceptual claim. If it
seems too weak, see if there are any hedges or qualifications that should be
taken out. If it instead seems too strong, consider adding these.

4. **Read Chapters 9 and 10 of *The Craft of Research*.**

These chapters describe how to build your argument through evidence and reasons
to support your claim, as well as qualifications and acknowledgments when
needed.

5. **Identify evidence, reasons, acknowledgments in example papers.**

Re-read the two first paragraphs in the Chelygina et al. paper: 

> "Twitter is one of the most popular social media platforms, with over 320
million active users as of February 2019. Twitter users can enjoy free content
delivered by other users whom they actively decide to follow. However, unlike in
other areas where Twitter is used passively (e.g., to follow influential figures
and/or information agencies), in science it can be used in a much more active,
collaborative way: to ask for advice, to form new bonds and scientific
collaborations, to announce jobs and find employees, to find new mentors and
jobs. This is particularly important in the early stages of a scientific career,
during which lack of collaboration or delayed access to information can have the
most impact. 

> "For these reasons, using Twitter appropriately [1] can be more than
just a social media activity; it can be a real career incubator in which
researchers can develop their professional circles, launch new research projects
and get helped by the community at various stages of the projects. Twitter is a
tool that facilitates decentralization in science; you are able to present
yourself to the community, to develop your personal brand, to set up a dialogue
with people inside and outside your research field and to create or join
professional environment in your field without mediators such as your direct
boss."

Based on the key claim you identified earlier for these paragraphs, write down
the reasons that the text gives to support that claim. Write these down by 
first writing the claim in bold and then providing a bulleted list with 
each key reason they give in support of that claim (you can put these in 
the order they're given in the text, but you don't have to).

Assess these reasons. What evidence do they give in support of these reasons?
Are there any where they assume that no evidence is needed, because the reason
is commonly accepted as valid? Can you identify any qualifications /
acknowledgments that are included in their argument in support of the key claim
or any of the reasons they provide for the main claim?

Next answer the same questions for the paragraph from the Gall et al. paper: 

> "A more subtle form of introducing hazard bias arises from issues of the
definition of the hazard and assigning loss estimates (by the original data
source) to predefined hazard categories within a database. This is most apparent
in the management of complex events involving multiple hazards versus a singular
hazard event. A tornado spawned by a hurricane is counted as a unique tornado
event, but it could also be lumped together within the entire hurricane event,
or both. Each loss database classifies events differently, especially when they
involve multiple hazard types (Guha-Sapir and Below 2002). Inconsistent naming
conventions and classification methodologies aggravate this problem and can
result in different (and/ or artificial) hazard categories for similar, if not
identical events. For example, Downton et al. (2005) reveal a $520 million
"flood" loss in FEMA's database that was not in the NWS data. The discrepancy is
a result of differences in how each agency defines what constitutes a flood
event. In this case, the event (storm surge) was outside NWS's definition of a
flood."

6. **Identify evidence, reasons, and acknowledgments in example papers.**

Use the paragraph from your manuscript that you used for prompt 3. Write out
the key claim and the reasons you give to support it, using the same style as
for the last prompt. 

Evaluate these reasons using the same questions as in the last prompt. What
evidence do you give in support of these reasons? Are there any where you assume
that no evidence is needed, because the reason is commonly accepted as valid?
Are there any qualifications / acknowledgments that are included in their
argument in support of the key claim or any of the reasons you provide for the
main claim?

Revise the paragraph based on your assessment. If there are areas where you need
more reasons or evidence, you can put placeholders in to note what's missing and
do more research later to fill those in.

7. **Read Chapter 11 of *The Craft of Research*.**

This chapter explains when and how to include warrants in your arguments, to 
connect reasons to claims. In student's writing, there are often too few warrants. 
I think this might be because students often think that their reader will know
at least as much as they do about the topic, and so if the connection is obvious
to the student it must also be to the reader. 

Remember that this is no longer the case. For your scientific manuscripts, you 
will be the expert in the room. You will know more about the very specific topic
than almost all the readers, possibly including the editor and reviewers for the
peer review process. Connections that seem obvious to you will not have occurred
to many of them. 

8. **Add a warrant in an example paper.**

In the Chelygina et al. paper, the claim is made that: 

> "Using Twitter appropriately ... can be a real career incubator"

One of the reasons that they give is:

> "In science [Twitter] can be used in a much more active,
collaborative way: to ask for advice, to form new bonds and scientific
collaborations, to announce jobs and find employees, to find new mentors and
jobs."

To connect this reason with their claim, they provide the following warrant:

> "This is particularly important in the early stages of a scientific career,
during which lack of collaboration or delayed access to information can have the
most impact."

Explain how this warrant connects this reason to the key claim they make.

Another of the reasons that they give, but for which they do not provide a 
warrant, is: 

> "Twitter users can enjoy free content delivered by other users whom they
actively decide to follow."

Rewrite the first two paragraphs of their introduction to add a warrant
connecting this reason to the main claim. Do you think this added warrant is
necessary, or will it be clear to most readers how they connect without it?

9. **Add warrants to your manuscript.**

Revisit the paragraph from your manuscript that you used for prompts 3 and 6. 
Do you give a warrant for every reason that you provide for your key claim 
in that paragraph? If not, pick the warrant-less reason for which you think the
connection will be the least obvious for reader and add a warrant. 

In re-reading the paragraph, do you think this warrant is useful or unnecessary?
Skim through other paragraphs in your manuscript and find 2--3 other places
where a warrant might be helpful and add one.

**All the following steps are things for you to try after our workshop 
meeting on "Arguments".**

10. **Identify and revise more claims in your manuscript.**

Repeat prompt 3 for more paragraphs in your manuscript. Once you have assessed
and revised more of your claims, highlight all of the key claims that you are
making in the manuscript. This will help in assessing the overall structure of
the manuscript and how solid your key arguments are.

For the paragraphs or sections with the most important of these claims, repeat
prompt 6 to diagnose and fix any problems in your argument for the claim.

11. **Re-read Chapters 8 and 9 of *Writing Science*.**

These chapters talk about how to write the middle and end of a scientific
manuscript, which the author calls the "Action" and the "Resolution".
At a high level, your manuscript makes its main claim through its
Challenge at the end of the Opening. This is where it claims that 
it will address an important problem. The rest of the paper works to 
build the argument for this claim by providing evidence, warrents, 
qualifications, etc. 

12. **Diagnose for your manuscript if the Action and Resolution support the claim made by the Challenge.**

Yesterday, you identified the issues in each of the paragraphs in your
manuscript. Think about how, at a broad level, these issues contribute to the
"claim" that the Challenge of your paper makes. Does your Challenge agree in
topic and scope with what's written in the rest of your manuscript? If not, do
you think that you should revise the Challenge, or would it be better to edit
the rest of the manuscript to better support the Challenge? Can you identify
places where your current argument is weak in the paper as a whole?

13. **Read Chapter 18 of *Writing Science*.**

This chapter describes how to discuss limitations of your research in a
manuscript. In *The Craft of Research*, we read about the importance of
qualifications. In a scientific manuscript with original research, some of your
"arguments" will be the interpretation you give for your results. Some of the
qualifications/acknowledgments for these arguments will come through your
discussion of the limitations of the study.

14. **Draft text on limitations for your study.**

Think about your own manuscript. Does it describe original research for which
you should describe study limitations? (This may not be the case if you
manuscript is a commentary or editiorial.) If so, what are some of the key
limitations of the study? Think of these in terms of things that you would fix
if it were practical.

Draft some text that first describes each of these limitations and then explains
why you didn't avoid them in the research (for example, the alternative could
not practically be done, or they were unlikely to influence the results much).

If your paper does not cover original research, think of some other high-level
qualifications that it may be important to make in your paper. It may be helpful
to think of which comments you're most worried about getting from reviewers.

15. **Read Chapters 13, 15, and 16 of *The Craft of Research*.**

These chapters give more guidance on how to put all these pieces together in
writing. They include advice on how to present evidence visually, through tables
and figures in the paper, as well as how to reorganize and edit large parts of
your text, especially the Introduction and Conclusions, to improve arguments.