# Day 5: Words

`r newthought("We'll wrap up by talking about")` editing you can do at the level
of words. I find this to be the easiest and most fun type of editing. A lot of
it doesn't take a lot of mental work, but your writing immediately feels much
lighter! 

A lot of the advice in this section will have a secondary benefit---it will 
reduce the number of words it takes you to say something. In scientific writing, 
we often have to fit our final work within a constrained word count or page limit. 
Since we want to have high-impact, high-content papers, this can be a big 
struggle. The suggestions today will help with this. 

The other key point for today is how word choices can make your writing
easier to read and understand. There are two key angles here. First, you want
to identify the "terms of art" in your paper. What are the technical terms
that mean something very specific, and that you can't simplify without losing
important subtlety? For these words, you must make sure that (1) you're using
the right term for your field and (2) you consistently use the same term for that
idea. Second, you have all the other words in your paper, the ones that aren't 
terms of art. Scientific reading is hard enough just because of the scientific
content. Therefore, I feel strongly that you should try to make all these other
words---the ones that aren't terms of art---as simple as possible. Therefore, 
part of the editing process at the word level will be to simplify any vocabulary
that doesn't absolutely have to be more complex. 

The techniques we'll cover today are outlines in several of the books---*Style* has
a chapter on "Concision" that we'll cover, and *Writing Science in Plain English* and
*Writing Science* both have helpful chapters. 

1.  **Read Chapter 7 from *Style* (same chapter in the second edition) and Chapter 6 from *Writing Science in Plain English.**

These two chapters cover how to remove needless words from your writing. Both cover
several ways that words can be redundant.

*Additional reading.* If you would like more information on the ideas in these
chapters of *Style*, you can also check out Chapter 16 from *Writing Science*.

2. **Diagnose and fix word redundance in paragraphs from example papers.**

On an earlier day, we looked closesly at the following paragraph from the Schwartz
paper: 

> "The question of disease etiology is complex. It is likely that a multitude of
causes is involved in the development of any particular disease. Where in the
causal chain, among the myriad of variables, one chooses to examine and
ascertain causation is often a question of where intervention is most
efficacious. That, in turn, is often a political and not a scientific issue. An
examination of the full range of variables potentially involved in disease
etiology, with a synthesis of findings from all levels of analysis, provides the
best opportunity for a full understanding of disease etiology."

Based on what you just read, identify words in this text that might be redundant. 
Try re-writing the text to remove those redundant words. You can either keep the
same structure for the paragraph otherwise, or you can start from the re-written
version of this paragraph you created on an earlier day.

Do the same exercise with the following paragraph from the Cheplygina et al. paper:

> "But even more importantly, Twitter culture has exposed a part of academia
that has traditionally always been hidden from view, namely the inception of new
research activities. Now, ECRs can observe and even join the process of creating
national or international research projects (for instance, [6] stems from a
discussion at Twitter and Bik et al [1] write their work resulted from online
interactions). Senior researchers openly share ideas through Twitter and this
can lead to the development of new concepts which often move on to become
fully-fledged research projects."

3. **Diagnose and fix redundant words in your manuscript.**

Pick a string of three or four paragraphs in your manuscript. Go carefully through
each type of redundancy described in the reading from prompt 1. Identify any 
cases in your paragraphs and fix them. 

For some of these, you can use the "Search" tool to search for potentially redundant
words. For example, you can do a search for meaningless words like "actually", 
"really", and "various". To look for doubled words, it might be helpful to do a 
search for "and". If you're struggling with some of the other types of redundancies, 
you might want to look through some of the many online lists with examples, 
including: https://www.dailywritingtips.com/50-redundant-phrases-to-avoid/, 
https://forge.medium.com/close-proximity-end-result-and-more-redundant-words-to-delete-from-your-writing-3258be693a3d, 
https://kathysteinemann.com/Musings/redundant/, and
https://www.thoughtco.com/common-redundancies-in-english-1692776. 

4. **Read Chapter 15 from *Writing Science* and Chapter 5 from *Writing Science in Plain English*.**

These two chapters cover how to choose the word to use for words that must
stay---the ones that aren't redundant. They cover two important ideas. First,
there are some words that mean something very specific in your field, and that
provide an immediate way to get a specific and often subtle idea across to
readers who have been trained in your field. For these words, you need to make
sure you are using the right term, and you don't want to simplify them because
they lose their precise and subtle meaning.

However, typically these words will be only a minor proportion of all the words
in your manuscript. It is easy for jargon or unneccessarily fancy words to creep
in everywhere else. Again, you are writing to describe ideas and findings that
are very complex. It will be hard for readers to process those ideas. To help
them a little, please, please, please try to make everything surrounding and
supporting those ideas as simple and clear as you can. If you worry that your
edited version of the manuscript is going to make you "sound dumb" because it 
sounds so simple, then you are on the right track! 

Also---and this is something that I continue to feel when I edit my own
papers---when you edit to clarify and simplify, you may sometimes feel exposed
or unprotected, because your idea is just out there for anyone to understand,
not in the shadow behind fancy words or sentence constructions. If you've edited
your manuscript well, you should feel a bit exposed. You're giving people a look
right into your head, and they'll be able to evaluate your ideas for what they
are. This is a normal feeling, and it feels scary, but it means you're on to
something good. If the idea itself is bad, you'll now see that more clearly and
be able to fix it. If it's a good idea, then other people will be able to grasp
it.

5. **Identify technical terms versus jargon in a paragraph from an example paper.**

Re-read the following paragraph from the Gall et al. paper:

> "Natural hazard losses exhibit an upward trend over time (Fig. 2). This is a
function of increases in wealth and population (Cutter and Emrich 2005; Pielke
et al. 2008) but is also attributed to better loss accounting in recent years.
The escalating pattern of hazard losses is therefore partially an artifact of
advances in reporting losses, but how much or how little this effect contributes
to the skyrocketing losses in comparison to effects of population growth and
increasing wealth in high hazard areas is unclear."

Make a list of the terms in this paragraph that you think are technical terms, 
as defined on page 147 of *Writing Science*. Then, highlight any terms that you 
think might be jargon, again using the definition from *Writing Science*. 

For each term in the "technical terms" list, write down what you think it's 
specific definition is. Look earlier in the paper. Is the term specifically 
defined or explained by the authors earlier in the manuscript?

Finally, revise the paragraph to replace all the jargon terms with simpler language. 

6. **Identify technical terms necessary in your manuscript.**

Go through your entire manuscript and make a glossary of the technical terms
that you *must* use in the manuscript. These might be proper nouns, like the
name of a specific package repository like "CRAN" or a database like "NOAA Storm
Events". They may be ideas that are  very specific to your topic, like
"reproducibility" or "exposure misclassification". In your glossary, include
both the term and your definition for it.

7. **Diagnose and fix jargon in your manuscript.**

Use the same paragraphs from your manuscript that you did for prompt 3.
Highlight any terms in these paragraphs that are in the glossary you created in
the last prompt. Now look at all the remaining words. Are any more complex than
they need to be? Identify jargon and revise the paragraphs to use simpler words.

**All the following steps are things for you to try after our workshop 
meeting on "Words".**

8. **Ensure that you are using the right technical terms in your manuscript.**

Go through the glossary you created in prompt 6. Look up each term in a reliable
source for your discipline. Sources to check include text books, field-specific
dictionaries (e.g., "Dictionary of Epidemiology"), and papers from well-respected
journals in your field. Does your definition match that definition? Are there 
other terms that might better match the idea you're trying to convey?

Next, once you are confident that the terms are right for your field, check to 
see if they mean something else in different fields. This can be a source of
confusion for readers (including reviewers!) who immediately think your term 
means one thing when it means something else. "Model" is one example---in 
biological sciences, this term may convey a model animal, while in statistics
it might convey a statistical model fit to data. You will not be able to catch 
all of these, but it's helpful to start identifying the terms that might mean
different things in different fields, as these might be terms that are worth 
re-defining in your manuscript so that readers are on the same page. 

9. **Add definitions in your manuscript for technical terms that readers might not know.**

Think about the audience you expect to read this paper, and then look through
your glossary. Are there words that readers might not know, based on the common
knowledge in the targeted audience? If so, find a place early in your manuscript
to provide these definitions. In some cases, you might follow the example of the
Cheplygina et al. paper and have an early section that gives terms and definitions
(their "Twitter terms" section). More often, you'll add in definitions as you get
to ideas, as Gall and coauthors do.  

10. **Diagnose and fix jargon and redundancy throughout your manuscript.**

Repeat prompts 3 and 7 for all the paragraphs in your manuscript. As you do, can
you identify redundancy and jargon that you tend to use pretty often? When you
write in the future, don't worry about these when you write your first drafts,
but if you get to know the problematic terms that you tend to use when drafting,
you can more quickly revise your later drafts to cut them out or replace them.

11. **Read Chapter 10 of *Style* (Chapter 2 of the second edition) and Chapter 8 of *Writing Science in Plain English*.**

These chapter cover editing in terms of correcting grammar and usage. These are
important topics, because your manuscript will seem less professional if it has
these mistakes, and so readers and reviewers might also question if your science
was done carefully and competently. However, we haven't focused much on these yet
because they are the easiest edits that co-authors can make as they edit your paper. 
You will want to learn these rules for yourself to avoid problems in writing for 
classes, cover letters for jobs, and so on, but I don't see them as a big barrier
in multi-author manuscripts, as long as one co-author who will read carefully can
find and fix them. This chapter is worth a read, though.

12. **Read Chapters 16 and 17 of *Writing Science*.**

These two chapters repeat and bring together some of the ideas we've covered
this week. They're helpful as you begin to move from the specific exercise we've
done here to working on broadly editing your manuscript.